### ISSUE TITLE
{{ globols:var }} Tag Pair?

### ISSUE THREAD

**Issue by zachphillips** [pixelfear/Statamic-Globals#2]
I have a suggest field and it's populating __globals.md properly, but as a tag pair it doesn't work, so {{ url }} and {{ title }} are just pulling from the page. Not sure if this has to do with the parse order?

**Comment by jasonvarga** [comment]
At the moment its not intended to work as a tag pair. You'd have to use the `get_content` method for that.  You can see an example of that at the bottom of the readme.

I'll look at adding support for this.

**Comment by zachphillips** [comment]
Thanks Jason.
