### ISSUE TITLE
Variable Modifiers

### ISSUE THREAD

**Issue by somwicked** [pixelfear/Statamic-Globals#4]
Trying to use a modifier on a global

```
{{ globals:email|obfuscate }}
```

Same as the conditionals, no output.

**Comment by jasonvarga** [comment]
This is a plugin tag, not a variable. It's just a helpful shorthand to output a value.

You can only use modifiers on actual variable tags.

You can use the regular `get_content` technique at the bottom of the readme if you need to access variables.
