### ISSUE TITLE
Date format isn't applied

### ISSUE THREAD

**Issue by alehandrof** [pixelfear/Statamic-Globals#5]
Similar to #3 & #4:

I wanted to do something like: `{{ globals:deadline format="F jS, Y" }}` but the format parameter is ignored and  the output is in the form of YYYY-MM-DD.

**Comment by jasonvarga** [comment]
This is a plugin tag, not a variable. It's just a helpful shorthand to output a value.

You can only use modifiers on actual variable tags.

You can use the regular `get_content` technique at the bottom of the readme if you need to access variables.

**Comment by alehandrof** [comment]
Cool. Thanks for the clarification, both here and on #3. You may have inadvertently suggested how to solve an issue I had with the var add-on.

I'm still a bit fuzzy on the distinction in usage between plugins and variables, but I trust it will make sense in time :)

Might be worth adding your reply to this issue and #3 on the README.
